### ISSUE TITLE
When readonly, you can't unset the value

### ISSUE THREAD

**Issue by andrejm** [WebDevStudios/CMB2-Post-Search-field#13]
I want users to only search for ids of attached post, **not to be able to write into the field directly** (the reason being confusion as what to write there).

When I add readonly attribute:

```
$related_device->add_field( array(
	    'name'        => __( 'Connect this post with device ID', 'theme' ),
	    'description' => __('Click on the magnifying glass to search for a device in catalogue.', 'theme'),
	    'id'          => $prefix . 'related_device',
	    'type'        => 'post_search_text', // This field type
	    // post type also as array
	    'post_type'   => 'device',
	    // or checkbox, used in the modal view to select the post type
	    'select_type' => 'radio',
	    'attributes'  => array(
			'readonly' => 'readonly',
		),
	) );
```

I find myself in situation, when the field **can't be cleared once the post ID is chosen**.

The solution might be to add another "clearing" button next to the magnifying glass or somehow add "none" option to overlay.

I myself will probably go for the clearing button - if this is preferred solution for this plugin, I can make a pull request when ready.

**Comment by jtsternberg** [comment]
I added an example to [the readme](https://github.com/WebDevStudios/CMB2-Post-Search-field#example) to change the select behavior to replace (instead of add) (using the `'select_behavior'` field parameter). This will probably help you.

**Comment by andrejm** [comment]
Thanks Justin, this definitely helps. Still no way to clear the field if readonly, but the replace bahaviour is a good option for my case. Closing now, in case I will come up with clearing solution, I will post/add PR.
