### ISSUE TITLE
Post Search Field doesnt work when it is in a group

### ISSUE THREAD

**Issue by ahm-3d** [WebDevStudios/CMB2-Post-Search-field#2]
i am trying to get the post search field to be within a repeatable group and to only allow me select 1 post from the list. i assume it is simple enough to change the checkboxes to radio to limit my selection but the main problem i am having is that the post search field doesn't display when it is with in a group.
how do i fix this?

**Comment by clovepod** [comment]
I've run into the same issue. I discovered that if there's a post search field outside of the repeatable group, all post search fields, both in and out of the group, work perfectly.

**Comment by feliksby** [comment]
The same trouble. Please make this field repeatable.

**Comment by jtsternberg** [comment]
This should be good w/ these updates: https://github.com/WebDevStudios/CMB2-Post-Search-field/compare/a3462ee342858d3169ff0078d56e4d8de8b026ae...master
